### ISSUE TITLE
Error in mstToCC(st[, 1:2], st[, 3]): Please use a 0-based MST

### ISSUE THREAD

**Issue by slowkow** [peekxc/clustertree#3]
Thanks for creating this package! I wanted to try it out but I ran into errors trying to run the examples from your README.

Do you know what might be the problem?

```r
library("clustertree")
data("iris")
x <- as.matrix(iris[, 1:4])
ct2 <- clustertree(x, k = 15L, alpha = sqrt(2), estimator = "KNN")
```

```
Error in mstToCC(st[, 1:2], st[, 3]): Please use a 0-based MST
Traceback:

1. clustertree(x, k = 15L, alpha = sqrt(2), estimator = "KNN")
2. mstToCC(st[, 1:2], st[, 3])
```

**Comment by peekxc** [comment]
Hi @slowkow, thanks for bringing this up. Sorry for the slow response, I was out of town the last two weeks. 

I've pushed up some changes that should fix this. It was a minor indexing issue. If you have any other issues, please do let me know!

**Comment by peekxc** [comment]
Hi @slowkow, 

I'm going to tentatively close this issue as fixed, as the example you gave should now run fine. If you run into any other issues, be sure to let me know!
